  
version: 0.2

phases:
    install:
        runtime-versions:
            docker: 18
    pre_build:
        commands:
        - npm install typescript --g
        - npm install yarn --g
        - yarn install
    build:
        commands:
        - yarn build
artifacts:
    type: zip
    files:
        - package.json
        - yarn.lock
        - tsconfig.json
        - Dockerrun.aws.json
        - 'dist/**/*'
        - Dockerfile