version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g typescript
      - npm install -g yarn
      - npm install -g tsdx
  pre_build:
    commands:
      - echo Prebuild
  build:
    commands:
      - echo Build started on `date`
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
cache:
  paths:
    - node_modules/**/*
artifacts:
  files: 
    - '**/*'